
export const GET_WEBHOOK_MESSAGE = 'GET_WEBHOOK_MESSAGE';
export const SET_WEBHOOK_URL_MESSAGE = 'SET_WEBHOOK_URL_MESSAGE';
export const GET_WEBHOOK_MESSAGE_RESPONSE = 'GET_WEBHOOK_MESSAGE_RESPONSE';

export const GET_NAME_MESSAGE = 'GET_NAME_MESSAGE';
export const GET_NAME_MESSAGE_RESPONSE = 'GET_NAME_MESSAGE_RESPONSE';

export const UPDATE_NAME_MESSAGE = 'UPDATE_NAME_MESSAGE';
export const UPDATE_WEBHOOK_MESSAGE = 'UPDATE_WEBHOOK_MESSAGE';

export const SLACK_KEY = 'slack_name';
export const WEBHOOK_URL = 'webhook_url';

export const SAVE_WEBHOOK_URL = 'SAVE_WEBHOOK_URL';

export const POST_CR_MESSAGE = "POST_CR_MESSAGE";

export const SAVE_KEY = 'SAVE_KEY';
export const SAVE_KEY_RESPONSE = 'SAVE_KEY_RESPONSE';
export const GET_KEY = 'GET_KEY';
export const GET_KEY_RESPONSE = 'GET_KEY_RESPONSE';
export const UPDATE_KEY = 'UPDATE_KEY';

